services:
  - type: web
    name: santa-rita-escolar
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: AUTH0_ISSUER
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
      - key: AUTH0_REQUIRED_SCOPE
        value: santa:use
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: BITACORA_SPREADSHEET_ID
        value: 13QYo-Dx23LPzKbY7szrz1HWyOMgQwKP5_oriGKKCNnA
      - key: SIEWEB_BASE_URL
        value: https://santaritadecasia.sieweb.com.pe
      - key: SIEWEB_USER
        sync: false
      - key: SIEWEB_PASSWORD
        sync: false
