FIREBASE_APPLICATION_ID=1:562272595963:android:65d896db19bbd969f7655e
FIREBASE_API_KEY=AIzaSyD15VjkrpLW5sroikO8enlnRNiOIMCNFjU
FIREBASE_PROJECT_ID=math-battle-63367
FIREBASE_STORAGE_BUCKET=math-battle-63367.firebasestorage.app
WEB_CLIENT_ID=562272595963-vpn1oans4nl0o27ebhblkt5pgbdl4b61.apps.googleusercontent.com
